### ISSUE TITLE
为什么你这代码迁移到swift项目中就有顶部点击不了的问题。。

### ISSUE THREAD

**Issue by ChinaArJun** [ArchLL/HGPersonalCenter#1]
为什么你这代码迁移到swift项目中就有顶部点击不了的问题。。

**Comment by qiaoyijie** [comment]
请问解决了吗？

**Comment by ArchLL** [comment]
@ChinaArJun 可能是哪里写错了吧

**Comment by ArchLL** [comment]
在**CenterTouchTableView**这个类中要主动去服从**UIGestureRecognizerDelegate**这个代理协议，如果这个类是OC编写的则不需要。

**Comment by ArchLL** [comment]
> 为什么你这代码迁移到swift项目中就有顶部点击不了的问题。。

在CenterTouchTableView这个类中要主动去服从UIGestureRecognizerDelegate这个代理协议

**Comment by ArchLL** [comment]
> 请问解决了吗？

在CenterTouchTableView这个类中要主动去服从UIGestureRecognizerDelegate这个代理协议，如果这个类是OC编写的则不需要。
