### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Chenggd** [ArchLL/HGPersonalCenter#2]
根据思路实现了一遍之后发现了一个bug,当添加下拉刷新or下拉回弹操作之后，uitableview的第一次点击事件会失效，第二次点击才会有效，mainTableview 的 shouldRecognizeSimultaneouslyWithGestureRecognizer 方法可以看出，若不在底部区域内不启用多手势下拉则不会有问题，若启用就会出现这个问题～～

我下载了demo,发现同样有这个问题。

**Comment by Chenggd** [comment]
> 根据思路实现了一遍之后发现了一个bug,当添加下拉刷新or下拉回弹操作之后，uitableview的第一次点击事件会失效，第二次点击才会有效，mainTableview 的 shouldRecognizeSimultaneouslyWithGestureRecognizer 方法可以看出，若不在底部区域内不启用多手势下拉则不会有问题，若启用就会出现这个问题～～
> 
> 我下载了demo,发现同样有这个问题。

**Comment by lancelot9527** [comment]
老哥，你这个问题怎么解决的。同样遇到这个问题

**Comment by Chenggd** [comment]
> 老哥，你这个问题怎么解决的。同样遇到这个问题

https://github.com/ArchLL/PersonalCenter-Extend/issues/1

**Comment by lancelot9527** [comment]
3q
