### ISSUE TITLE
严重的问题

### ISSUE THREAD

**Issue by monkeyDluffy1016** [ArchLL/HGPersonalCenter#6]
在ios12下，下面的tableview   didscrollview一直会滚动，会在主线程卡死。不能点击任何事件

**Comment by ArchLL** [comment]
如果你能在我的demo中复现这个问题，请说明测试设备的系统版本以及你具体的操作步骤，我会努力去解决；如果是你运用到你的项目中出现的问题，请你再仔细检查一下自己的代码，如果还不能解决，你也可以详细说明你遇到的问题，我尽量提供一些帮助。
